export const PromptData: string[] = [
    "A futuristic cyberpunk city glowing at night with neon lights",
    "A cozy cottage in the middle of a magical forest with glowing plants",
    "An astronaut discovering an alien civilization on a distant planet",
    "A steampunk-inspired mechanical dragon flying over London",
    "A majestic waterfall hidden deep inside a tropical jungle",
    "A fantasy warrior wielding a flaming sword in battle",
    "A Viking longship sailing through a stormy sea",
    "A samurai warrior standing under cherry blossom trees at sunset",
    "A mysterious ancient temple lost in the mountains",
    "A high-tech robot chef cooking gourmet dishes",
    "A futuristic racing car speeding through a cyber highway",
    "A neon-lit Tokyo street with people wearing sci-fi outfits",
    "A medieval castle floating in the sky among the clouds",
    "A pirate ship sailing towards a glowing treasure island",
    "An enchanted book that creates magical creatures when opened",
    "A phoenix rising from the ashes in a fiery explosion",
    "A cybernetic soldier in a battle against rogue AI machines",
    "A peaceful Japanese Zen garden with koi fish swimming",
    "A floating island with waterfalls pouring into the sky",
    "A futuristic city submerged under the ocean",
    "An alien landscape with giant glowing mushrooms",
    "A fantasy castle surrounded by dragons and mystical creatures",
    "A lost civilization with golden pyramids in the jungle",
    "A knight in shining armor standing in front of a magical portal",
    "A hidden treasure cave filled with sparkling gems and gold",
    "A surreal dream world with floating islands and impossible architecture",
    "A superhero flying over a futuristic metropolis at night",
    "A haunted mansion with glowing ghostly figures",
    "A giant tree with a village built inside its branches",
    "A fairytale princess in a gown made of stardust",
    "A mechanical city powered by giant clockwork gears",
    "A beautiful cybernetic mermaid swimming in neon waters",
    "A portal to another dimension opening in a forest clearing",
    "A shadowy figure standing in a rainy noir-style city",
    "A wise old wizard casting a powerful spell",
    "A futuristic soldier in advanced exoskeleton armor",
    "A race of intelligent robots living peacefully with humans",
    "A ninja warrior disappearing into a smoke bomb",
    "A winter wonderland with glowing ice castles",
    "A spaceship landing on an undiscovered planet",
    "A Victorian-era scientist creating a monstrous experiment",
    "A legendary sword stuck in a glowing crystal cave",
    "A cyber ninja fighting against evil AI overlords",
    "A mystical deer with glowing antlers in a moonlit forest",
    "A futuristic AI assistant manifesting in holographic form",
    "A time traveler witnessing dinosaurs in prehistoric Earth",
    "A dark gothic cathedral filled with mysterious figures",
    "A floating steampunk airship above a city in the clouds",
    "A post-apocalyptic world where nature has reclaimed civilization",
    "A magical portal in a library that leads to another universe",
    "A battle between ancient gods in a celestial sky",
    "A lost astronaut floating in deep space with a broken ship",
    "A street artist creating a graffiti that comes to life",
    "A detective solving a cyber-crime in a futuristic city",
    "A scientist discovering a parallel universe in a lab",
    "A surreal painting that transforms reality around it",
    "A biomechanical alien creature in a sci-fi horror scene",
    "A robotic samurai in a duel against another machine warrior",
    "A crystal cave glowing with mysterious ancient energy",
    "A lonely lighthouse keeper watching a stormy ocean",
    "A golden hour landscape with rolling fields of sunflowers",
    "A music festival in an alien world with floating stages",
    "A mythical sea serpent emerging from a glowing ocean",
    "A dystopian city ruled by robotic enforcers",
    "A circus with supernatural performers and magical acrobatics",
    "A futuristic subway station with neon graffiti and cybernetic passengers",
    "A dragon resting inside a volcano filled with gold",
    "A sentient AI becoming self-aware inside a quantum computer",
    "A village in the clouds where people live on floating platforms",
    "A cat wearing a tiny astronaut suit floating in space",
    "A magician pulling a rabbit out of a portal instead of a hat",
    "A mechanical angel descending from a futuristic heaven",
    "A forest spirit watching over a magical glade",
    "A medieval blacksmith forging a sword with magical runes",
    "A secret underwater city glowing with bioluminescent lights",
    "A modern-day samurai blending traditional and futuristic armor",
    "A high-speed hoverboard race through a cyberpunk city",
    "A surreal cosmic dream with planets merging into each other",
    "A neon-lit bar where aliens and humans socialize",
    "A futuristic knight riding a robotic horse into battle",
    "A giant octopus attacking a pirate ship under moonlight",
    "A vampire king ruling over a city of darkness",
    "A massive library filled with books that whisper knowledge",
    "A ghostly train traveling through an abandoned landscape",
    "A desert nomad discovering an ancient alien relic",
    "A fairy tale village hidden inside a giant mushroom forest",
    "A futuristic fashion show featuring holographic outfits",
    "A time traveler stuck in a loop between different eras",
    "A giant space whale swimming through the galaxy",
    "A glowing cybernetic butterfly landing on a robot’s hand",
    "A holographic DJ performing at a futuristic concert",
    "A celestial dragon made of pure stardust flying through space",
    "A peaceful alien monk meditating on a floating rock",
    "A mech warrior piloting a massive robotic battle suit",
    "A glowing neon forest where plants emit soft light",
    "A sorceress summoning a powerful spirit with magic symbols",
    "A lonely AI watching over a deserted Earth",
    "A beautiful digital garden where flowers grow from data streams",
    "A mysterious masked figure in a futuristic dystopian society",
    "A sci-fi explorer navigating a zero-gravity asteroid field",
    "A candy land where everything is made of glowing sweets",
    "A floating crystal palace high above the mountains",
  ];
  