import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
import { AnimatePresence } from "framer-motion";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Provider from './provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Providers>
            <Provider>
              <AnimatePresence mode="wait"> {/* Optional mode prop */}
                {children}
              </AnimatePresence>
            <ReactQueryDevtools initialIsOpen={false} />
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
